### ISSUE TITLE
Swagger/OpenAPI spec codegen error, missing rest package

### ISSUE THREAD

**Issue by deepakkapoor23** [automatiko-io/automatiko-engine#446]
Build failure due to missing rest package.
I am running the DSL workflows example that uses petstore swagger api to generate rest classes for service invocation from the workflow. The same error is seen with other examples that use open API spec.

Build logs show the swagger file being processed with automatiko instructions on how to override url etc yet no files are written to disk.

io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.automatiko.engine.quarkus.deployment.AutomatikoQuarkusProcessor#generateClassesFromResourcesStep threw an exception: java.lang.IllegalStateException: src/main/java/io/automatiko/engine/app/handlers/SwaggerPetstore_getPetById_restService_1_3_Handler.java:8: error: **package io.automatiko.engine.app.rest** does not exist
            io.automatiko.engine.app.rest.SwaggerPetstore service;
                                         ^,Note: src/main/java/io/automatiko/app/ApplicationProcesses.java uses unchecked or unsafe operations.,Note: Recompile with -Xlint:unchecked for details.
                at io.automatiko.engine.quarkus.deployment.AutomatikoQuarkusProcessor.compile(AutomatikoQuarkusProcessor.java:609)
                at io.automatiko.engine.quarkus.deployment.AutomatikoQuarkusProcessor.generateClassesFromResourcesStep(AutomatikoQuarkusProcessor.java:198)

**Comment by deepakkapoor23** [comment]
I am seeing this with both Maven and Gradle builds...

**Comment by mswiderski** [comment]
can you describe which example do you run or share your project?

**Comment by deepakkapoor23** [comment]
If I simply run this one DSL workflow where it needs to generate petstore rest service from swagger spec, I see this error

https://github.com/automatiko-io/automatiko-examples/blob/main/workflows-java-dsl/src/main/java/io/automatiko/examples/dsl/MyWorkflows.java#L99

Please see the attached sample project and try to build it with Maven command:
`mvnw clean package "-DskipTests"`

[automatiko-examples.zip](https://github.com/user-attachments/files/16379560/automatiko-examples.zip)

**Comment by mswiderski** [comment]
works without single issue
![image](https://github.com/user-attachments/assets/85000626-752e-415b-ac55-7c3913171b7a)

**Comment by deepakkapoor23** [comment]
Any idea what could be wrong in my environment? Can you please share your target folder, I'm curious what did it generate in the rest package.

**Comment by mswiderski** [comment]
there you go

![image](https://github.com/user-attachments/assets/a1b3bcde-aa9e-483f-8df0-6428e211bac5)

**Comment by deepakkapoor23** [comment]
Strange, that whole package is missing for me. Did you simply run the sample project I shared or had to change some properties?

**Comment by deepakkapoor23** [comment]
Same result in quarkus:dev mode, missing rest package.

**Comment by deepakkapoor23** [comment]
Guess what, I built it on Linux and it builds fine. So its indeed a Windows path issue.

**Comment by mswiderski** [comment]
hmm weird as it used to work on windows too. Will try to look into though might not be easy - don't have windows machine any more...
